language: r
warnings_are_errors: false
sudo: false
cache: packages
r: 3.6.1
r_packages:
- covr
- devtools
- testthat
bioc_packages:
- GenomicRanges
- VariantAnnotation
- DNAcopy
r_github_packages:
- mskilab/gUtils
- mskilab/gTrack
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- export R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
script:
- "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
after_success:
- travis_wait Rscript -e 'covr::codecov()'
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
